spring:
  application:
    name: dist-market-central
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

security:
  basic:
    enabled: false

adminAccount:
  username: admin
  password: admin