spring:
  application:
    name: dist-market-producer
  security:
    basic:
      enabled: false
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform:
      org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
server:
  port: 8863
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

marketplace:
  api:
    updateDataUrl: http://localhost:8762/api/v1/supplierData
    productManagementUrl: http://localhost:8762/api/v1/managedProducts